person:
 lastName: yang
 age: 22
 boss: true
 birth: 2020/09/21
 maps:
   k1: value1
   k2: value2
 lists:
   - one
   - two
   - three

dog:
  name: dogName
  color: black



rectangle:
  length: 20
  width: 30

mail:
  hostname: host@mail.com
  port: 9000
  from: mailer@mail.com
  defaultRecipients:
    - admin@mail.com
    - owner@mail.com
  additionalHeaders:
    redelivery: true
    secure: true
    p3: value

