server:
 port: 8081
spring:
  profiles:
    active: dev

person:
 lastName: yang
 age: 22
 boss: true
 birth: 2020/09/21
 maps:
   k1: value1
   k2: value2
 lists:
   - one
   - two
   - three
 dog:
   name: dogName
   age: 1

rectangle:
  length: 20
  width: 30

---
server:
  port: 8082
spring:
  profiles: dev

---
server:
  port: 8084
spring:
  profiles: prod